### ISSUE TITLE
ERROR: "Trying to thunk generic handle that has been shutdown already"

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi#448]
omi build: `\\redmond\wsscfs\OSTCData\Builds\omi\release\1.4.1-0`

**NOTE:** 1.3.0-2 also has this issue, but 1.2.0-35 don't have miclient.log.

**Repro Systems:**
Ubuntu 16.04 x64, Suse 12x64, Debian 9x64.
**NOTE:** No issue systems: Redhat7x64,CentOS7x64,Oracle7x64.

**Reproduce steps:**
1. Install omi
2. Run `while true; do /opt/omi/bin/omicli id; done`
3. Check `cat /var/opt/omi/log/miclient.log|grep ERROR` and you will see one new error "2017/11/19 23:48:04 [24799,24799] ERROR: null(0): EventId=20106 Priority=ERROR Trying to thunk generic handle that has been shutdown already: 0x7ffc9c3909f0" per new query.

Actual result: ERROR in miclient.log
Expect result: No error in miclient.log

**Comment by JumpingYang001** [comment]
https://github.com/Microsoft/omi/blob/15d9c277faa32511c9a2ca7ab20efbbaa93c536c/Unix/miapi/SafeHandle.c#L245
Currently it is a LOG_ERR, @jeffaco , can we easily modify it to LOG_INFO or we need to avoid "Handle is shutdown" status?

**Comment by JumpingYang001** [comment]
From @paulcallen : 
>Those client-side errors can usually be ignored. The could be an indication of closing an MI_Operation more than once, which is generally not good, but will not cause a crash unless done after closing an MI_Application. We will need to investigate the cause, but it should not be blocking of a release.

**Comment by palladia** [comment]
This problem was first observed on OMS, where statically linked libraries caused incompatibility with client.  This, and backward compatibility issues have been identified and fixed.

Are you still seeing this in latest version, 1.4.2+?

**Comment by JumpingYang001** [comment]
I will check it today, thanks.

**Comment by JumpingYang001** [comment]
@palladia , this is not related to OMS or backward compatibility, it was reproduced only with installing OMI, from 1.3.0-2 to latest release, it is still not fixed, thanks.

**Comment by palladia** [comment]
This may have been fixed.  Please verify again.

**Comment by JumpingYang001** [comment]
will verify it today.

**Comment by JumpingYang001** [comment]
we have verified on `\\redmond\wsscfs\OSTCData\Builds\omi\develop\1.4.3-105`, the issue still exist.

**Comment by JumpingYang001** [comment]
@AlbertWang44 , let me clarify clearly something:
1. "ERROR Trying to thunk generic handle that has been shutdown already", the error doesn't make any affect on memory or cpu load. it is a client side issue (aka omicli command).

2. omi contains many processes, e.g. omiserver, omiengine, omiagent.
If your 33% memory usage is omiagent, then it is not omi issue, it is provider issue. we have many providers at present. some providers are here: https://github.com/Microsoft/omi#omi-providers

**To check which exact process**: `ps -aux|grep omi`

**Comment by AlbertWang44** [comment]
Hi Jumping,

Thanks for your information!

The 33% is OMI not omiagent
[cid:image002.png@01D41EEC.FA63D9F0]

Best,
Albert Wang, Technical Support Engineer
Global Business Support, Asia Pacific & Greater China Region
TEL: +86 (21)5263 8224 | www.microsoft.com/microsoftservices<http://www.microsoft.com/microsoftservices>

[id:image002.png@01D35170.6ECFDE60]

**Comment by JumpingYang001** [comment]
Investigating.

**Comment by sarojcare** [comment]
Jumping will investigate the issue further.

**Comment by JumpingYang001** [comment]
After debugging, the issue repro on production, but when enabling debug, the issue has gone, I am investigating the difference.

Production with enabling debug:
```
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45291 Priority=DEBUG MI_Client Application Initialize: application=0x7ffe4d833100, internal-application=0x142a730
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45283 Priority=DEBUG Enter Application_NewSession with application (0x7ffe4d833100), protocol (null), destination(null), session (0x7ffe4d8330e0).
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45287 Priority=DEBUG Enter Session_Create with application (0x7ffe4d833100), protocol (null), destination(null), session (0x7ffe4d8330e0).
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45297 Priority=DEBUG MI_Client Session Create: application=0x7ffe4d833100, session=0x7ffe4d8330e0, internal-session=0x142ace0
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45284 Priority=DEBUG Leave Application_NewSession with session (0x7ffe4d8330e0).
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45289 Priority=DEBUG Enter Session_AccessCheck - session (0x7ffe4d8330e0)
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45290 Priority=DEBUG Leave Session_AccessCheck on session (0x7ffe4d8330e0) with for operation (enumerate instance).
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45311 Priority=DEBUG MI_Client Operation Enumerate Instances: session=0x7ffe4d8330e0, operation=0x7ffe4d832f20, internal-operation=0x142bcb0, namespace=root/omi, classname=OMI_Identify
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45154 Priority=DEBUG (U)Socket: 0x1434b60, All send
2018/08/20 03:21:55 [20372,20372] INFO: null(0): EventId=40032 Priority=INFO Selector_AddHandler: selector=0x7f8124927250, handler=0x1434b60, name=BINARY_CONNECTOR
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45146 Priority=DEBUG InteractionProtocolHandler_Session_Connect passed !
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45142 Priority=DEBUG InteractionProtocolHandler_Protocol_RunThread
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45005 Priority=DEBUG MessageFromBatch:- msg tag is 15, index: 15
2018/08/20 03:21:55 [20372,20373] INFO: null(0): EventId=40011 Priority=INFO (U)done with receiving msg(0x7f811c0008f8:15:BinProtocolNotification:0)
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45367 Priority=DEBUG (U)Handle:(0x1434b60), ClientAuthState = 3, EngineAuthState = 4
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45366 Priority=DEBUG Client: Client Credentials Verified
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45131 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_PostControl 0x142be30
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45132 Priority=DEBUG ==== InteractionProtocolHandler_Session_ConnectionEvents() PROTOCOLEVENT_CONNECT
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45148 Priority=DEBUG ProtocolSocket: Posting message for interaction [0x1434bd0]<-0x142bf78
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45206 Priority=DEBUG Sending msg(0x142fde8:4099:EnumerateInstancesReq:2711) on own thread
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45154 Priority=DEBUG (U)Socket: 0x1434b60, All send
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45134 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Ack 0x142be30
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45005 Priority=DEBUG MessageFromBatch:- msg tag is 2, index: 2
2018/08/20 03:21:55 [20372,20373] INFO: null(0): EventId=40011 Priority=INFO (U)done with receiving msg(0x7f811c0008f8:2:PostInstanceMsg:2711)
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45367 Priority=DEBUG (U)Handle:(0x1434b60), ClientAuthState = 4, EngineAuthState = 4
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45128 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Post: 0x142be30, msg(0x7f811c0008f8:2:PostInstanceMsg:2711)
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45151 Priority=DEBUG ProtocolSocket: Ack on interaction [0x1434bd0]<-0x142bf78
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45005 Priority=DEBUG MessageFromBatch:- msg tag is 4, index: 4
2018/08/20 03:21:55 [20372,20373] INFO: null(0): EventId=40011 Priority=INFO (U)done with receiving msg(0x7f811c002a28:4:PostResultMsg:2711)
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45367 Priority=DEBUG (U)Handle:(0x1434b60), ClientAuthState = 4, EngineAuthState = 4
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45128 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Post: 0x142be30, msg(0x7f811c002a28:4:PostResultMsg:2711)
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45129 Priority=DEBUG MI_Result = MI_RESULT_OK
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45301 Priority=DEBUG MI_Client Operation Instance Result (async): session=0x7ffe4d8330e0, operation=0x7ffe4d832f20, internal-operation=0x142bcb0, resultCode=0, moreResults=FALSE
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45289 Priority=DEBUG Enter Session_AccessCheck - session (0x142bce0)
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45290 Priority=DEBUG Leave Session_AccessCheck on session (0x142bce0) with for operation (close operation).
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45289 Priority=DEBUG Enter Session_AccessCheck - session (0x142bce0)
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45290 Priority=DEBUG Leave Session_AccessCheck on session (0x142bce0) with for operation (cancel operation).
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45308 Priority=DEBUG MI_Client Operation Cancel: operation=0x7ffe4d832f20, internal-operation=0x142bcb0
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45140 Priority=DEBUG InteractionProtocolHandler_Operation_Cancel 0x142be30 -- ignoring because we have already posted the final result
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45306 Priority=DEBUG MI_Client Operation Close: operation=0x7ffe4d832f20, internal-operation=0x142bcb0
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45286 Priority=DEBUG Shutting down thunk handle: 0x142be00
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45288 Priority=DEBUG Enter Session_Close with session (0x7ffe4d8330e0), completionContext ((nil)), completionCallback ((nil)).
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45289 Priority=DEBUG Enter Session_AccessCheck - session (0x7ffe4d8330e0)
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45290 Priority=DEBUG Leave Session_AccessCheck on session (0x7ffe4d8330e0) with for operation (close session).
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45299 Priority=DEBUG MI_Client Session Close: session=0x7ffe4d8330e0, internal-session=0x142ace0
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45286 Priority=DEBUG Shutting down thunk handle: 0x142add0
2018/08/20 03:21:55 [20372,20372] ERROR: null(0): EventId=20106 Priority=ERROR Trying to thunk generic handle that has been shutdown already: 0x7ffe4d8322d0
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45300 Priority=DEBUG MI_Client Session Close: waiting for all operations to shutdown session=0x7ffe4d8330e0, internal-session=0x142ace0, number left=1
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45126 Priority=DEBUG InteractionProtocolHandler_Client_Ack_PostToInteraction 0x142be30
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45138 Priority=DEBUG InteractionProtocolHandler_Operation_Close 0x142be30
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45305 Priority=DEBUG MI_Client Operation Close: Complete session=0x7ffe4d8330e0, operation=0x7ffe4d832f20, internal-operation=0x142bcb0
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45141 Priority=DEBUG InteractionProtocolHandler_Session_Close 0x142bc30 (CompletionCallback 0x7f8124768970)
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45145 Priority=DEBUG SessionCloseCompletion_Release 0x142bc90 count is 1
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45151 Priority=DEBUG ProtocolSocket: Ack on interaction [0x1434bd0]<-0x142bf78
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45152 Priority=DEBUG (U)ProtocolSocket: Close received (closed other: 0) on interaction [0x1434bd0]<-0x142bf78
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45147 Priority=DEBUG ProtocolSocket: triggering timeout on 0x1434b60
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45158 Priority=DEBUG (U)Protocol _RequestCallback: closing 0x1434b60 after mask 10
2018/08/20 03:21:55 [20372,20373] INFO: null(0): EventId=40012 Priority=INFO (U)Socket: 0x1434b60, closing connection (mask 10)
2018/08/20 03:21:55 [20372,20373] INFO: null(0): EventId=40033 Priority=INFO Selector_RemoveHandler: selector=0x7f8124927250, handler=0x1434b60, name=BINARY_CONNECTOR
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45159 Priority=DEBUG (U)Protocol _RequestCallback: removing 0x1434b60 (mask 20, prev: a)
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45349 Priority=DEBUG Sock_Close: sock (6)
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45136 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Close 0x142be30
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45137 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Finish 0x142be30
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45144 Priority=DEBUG SessionCloseCompletion_Release 0x142bc90 with CompletionCallback 0x7f8124768970
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45298 Priority=DEBUG MI_Client Session Close: Completed session=0x7ffe4d8330e0, internal-session=0x142ace0
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45292 Priority=DEBUG MI_Client Application Close: application=0x7ffe4d833100, internal-application=0x142a730
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45153 Priority=DEBUG (U)ProtocolSocket: 0x1434b60 _ProtocolSocket_Finish
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45065 Priority=DEBUG SelectorRun(Exit): 0x7f8124927250
2018/08/20 03:21:55 [20372,20373] DEBUG: null(0): EventId=45143 Priority=DEBUG InteractionProtocolHandler_Protocol_RunThread finished with return 0
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45349 Priority=DEBUG Sock_Close: sock (3)
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45349 Priority=DEBUG Sock_Close: sock (5)
2018/08/20 03:21:55 [20372,20372] DEBUG: null(0): EventId=45296 Priority=DEBUG MI_Client Application Close: completed application=0x7ffe4d833100, internal-application=0x142a730
```

Enabling debug, the issue has gone:
```
root@jumping-ub14:~# cat /home/jumping/omi/Unix/output/var/log/miclient.log
2018/08/20 04:14:49 [25008,25008] DEBUG: Application.c(301): EventId=45291 Priority=DEBUG MI_Client Application Initialize: application=0x7fffffffe530, internal-application=0x65c7b8
2018/08/20 04:14:49 [25008,25008] DEBUG: Application.c(624): EventId=45283 Priority=DEBUG Enter Application_NewSession with application (0x7fffffffe530), protocol (null), destination(null), session (0x7fffffffe550).
2018/08/20 04:14:49 [25008,25008] DEBUG: Session.c(139): EventId=45287 Priority=DEBUG Enter Session_Create with application (0x7fffffffe530), protocol (null), destination(null), session (0x7fffffffe550).
2018/08/20 04:14:49 [25008,25008] DEBUG: Session.c(326): EventId=45297 Priority=DEBUG MI_Client Session Create: application=0x7fffffffe530, session=0x7fffffffe550, internal-session=0x65da08
2018/08/20 04:14:49 [25008,25008] DEBUG: Application.c(646): EventId=45284 Priority=DEBUG Leave Application_NewSession with session (0x7fffffffe550).
2018/08/20 04:14:49 [25008,25008] DEBUG: Session.c(779): EventId=45289 Priority=DEBUG Enter Session_AccessCheck - session (0x7fffffffe550)
2018/08/20 04:14:49 [25008,25008] DEBUG: Session.c(805): EventId=45290 Priority=DEBUG Leave Session_AccessCheck on session (0x7fffffffe550) with for operation (enumerate instance).
2018/08/20 04:14:49 [25008,25008] DEBUG: Operation.c(1978): EventId=45311 Priority=DEBUG MI_Client Operation Enumerate Instances: session=0x7fffffffe550, operation=0x7fffffffe430, internal-operation=0x65df48, namespace=root/omi, classname=OMI_Identify
2018/08/20 04:14:49 [25008,25008] DEBUG: protocol.c(1711): EventId=45154 Priority=DEBUG (U)Socket: 0x667188, All send
2018/08/20 04:14:49 [25008,25008] INFO: ../sock/selector.c(233): EventId=40032 Priority=INFO Selector_AddHandler: selector=0x7ffff7dd9340, handler=0x667188, name=BINARY_CONNECTOR
2018/08/20 04:14:49 [25008,25008] DEBUG: InteractionProtocolHandler.c(1373): EventId=45146 Priority=DEBUG InteractionProtocolHandler_Session_Connect passed !
2018/08/20 04:14:49 [25008,25012] DEBUG: InteractionProtocolHandler.c(2456): EventId=45142 Priority=DEBUG InteractionProtocolHandler_Protocol_RunThread
2018/08/20 04:14:49 [25008,25012] DEBUG: messages.c(706): EventId=45005 Priority=DEBUG MessageFromBatch:- msg tag is 15, index: 15
2018/08/20 04:14:49 [25008,25012] INFO: protocol.c(1878): EventId=40011 Priority=INFO (U)done with receiving msg(0x7ffff0000920:15:BinProtocolNotification:0)
2018/08/20 04:14:49 [25008,25012] DEBUG: protocol.c(1880): EventId=45367 Priority=DEBUG (U)Handle:(0x667188), ClientAuthState = 3, EngineAuthState = 4
2018/08/20 04:14:49 [25008,25012] DEBUG: protocol.c(952): EventId=45366 Priority=DEBUG Client: Client Credentials Verified
2018/08/20 04:14:49 [25008,25012] DEBUG: InteractionProtocolHandler.c(468): EventId=45131 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_PostControl 0x6607d8
2018/08/20 04:14:49 [25008,25012] DEBUG: InteractionProtocolHandler.c(473): EventId=45132 Priority=DEBUG ==== InteractionProtocolHandler_Session_ConnectionEvents() PROTOCOLEVENT_CONNECT
2018/08/20 04:14:49 [25008,25012] DEBUG: protocol.c(300): EventId=45148 Priority=DEBUG ProtocolSocket: Posting message for interaction [0x667210]<-0x660968
2018/08/20 04:14:49 [25008,25012] DEBUG: ../sock/selector.c(365): EventId=45206 Priority=DEBUG Sending msg(0x662350:4099:EnumerateInstancesReq:2711) on own thread
2018/08/20 04:14:49 [25008,25012] DEBUG: protocol.c(1711): EventId=45154 Priority=DEBUG (U)Socket: 0x667188, All send
2018/08/20 04:14:49 [25008,25012] DEBUG: InteractionProtocolHandler.c(490): EventId=45134 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Ack 0x6607d8
2018/08/20 04:14:49 [25008,25012] DEBUG: messages.c(706): EventId=45005 Priority=DEBUG MessageFromBatch:- msg tag is 2, index: 2
2018/08/20 04:14:49 [25008,25012] INFO: protocol.c(1878): EventId=40011 Priority=INFO (U)done with receiving msg(0x7ffff0000920:2:PostInstanceMsg:2711)
2018/08/20 04:14:49 [25008,25012] DEBUG: protocol.c(1880): EventId=45367 Priority=DEBUG (U)Handle:(0x667188), ClientAuthState = 4, EngineAuthState = 4
2018/08/20 04:14:49 [25008,25012] DEBUG: InteractionProtocolHandler.c(251): EventId=45128 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Post: 0x6607d8, msg(0x7ffff0000920:2:PostInstanceMsg:2711)
2018/08/20 04:14:49 [25008,25012] DEBUG: protocol.c(338): EventId=45151 Priority=DEBUG ProtocolSocket: Ack on interaction [0x667210]<-0x660968
2018/08/20 04:14:50 [25008,25012] DEBUG: messages.c(706): EventId=45005 Priority=DEBUG MessageFromBatch:- msg tag is 4, index: 4
2018/08/20 04:14:50 [25008,25012] INFO: protocol.c(1878): EventId=40011 Priority=INFO (U)done with receiving msg(0x7ffff0002d60:4:PostResultMsg:2711)
2018/08/20 04:14:50 [25008,25012] DEBUG: protocol.c(1880): EventId=45367 Priority=DEBUG (U)Handle:(0x667188), ClientAuthState = 4, EngineAuthState = 4
2018/08/20 04:14:50 [25008,25012] DEBUG: InteractionProtocolHandler.c(251): EventId=45128 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Post: 0x6607d8, msg(0x7ffff0002d60:4:PostResultMsg:2711)
2018/08/20 04:14:50 [25008,25012] DEBUG: InteractionProtocolHandler.c(315): EventId=45129 Priority=DEBUG MI_Result = MI_RESULT_OK
2018/08/20 04:14:50 [25008,25012] DEBUG: Operation.c(944): EventId=45301 Priority=DEBUG MI_Client Operation Instance Result (async): session=0x7fffffffe550, operation=0x7fffffffe430, internal-operation=0x65df48, resultCode=0, moreResults=FALSE
2018/08/20 04:14:50 [25008,25012] DEBUG: InteractionProtocolHandler.c(170): EventId=45126 Priority=DEBUG InteractionProtocolHandler_Client_Ack_PostToInteraction 0x6607d8
2018/08/20 04:14:50 [25008,25012] DEBUG: protocol.c(338): EventId=45151 Priority=DEBUG ProtocolSocket: Ack on interaction [0x667210]<-0x660968
2018/08/20 04:14:50 [25008,25008] DEBUG: Session.c(779): EventId=45289 Priority=DEBUG Enter Session_AccessCheck - session (0x65df78)
2018/08/20 04:14:50 [25008,25008] DEBUG: Session.c(805): EventId=45290 Priority=DEBUG Leave Session_AccessCheck on session (0x65df78) with for operation (close operation).
2018/08/20 04:14:50 [25008,25008] DEBUG: Session.c(779): EventId=45289 Priority=DEBUG Enter Session_AccessCheck - session (0x65df78)
2018/08/20 04:14:50 [25008,25008] DEBUG: Session.c(805): EventId=45290 Priority=DEBUG Leave Session_AccessCheck on session (0x65df78) with for operation (cancel operation).
2018/08/20 04:14:50 [25008,25008] DEBUG: Operation.c(1335): EventId=45308 Priority=DEBUG MI_Client Operation Cancel: operation=0x7fffffffe430, internal-operation=0x65df48
2018/08/20 04:14:50 [25008,25008] DEBUG: InteractionProtocolHandler.c(691): EventId=45140 Priority=DEBUG InteractionProtocolHandler_Operation_Cancel 0x6607d8 -- ignoring because we have already posted the final result
2018/08/20 04:14:50 [25008,25008] DEBUG: Operation.c(1260): EventId=45306 Priority=DEBUG MI_Client Operation Close: operation=0x7fffffffe430, internal-operation=0x65df48
2018/08/20 04:14:50 [25008,25008] DEBUG: SafeHandle.c(207): EventId=45286 Priority=DEBUG Shutting down thunk handle: 0x660778
2018/08/20 04:14:50 [25008,25008] DEBUG: InteractionProtocolHandler.c(642): EventId=45138 Priority=DEBUG InteractionProtocolHandler_Operation_Close 0x6607d8
2018/08/20 04:14:50 [25008,25008] DEBUG: protocol.c(352): EventId=45152 Priority=DEBUG (U)ProtocolSocket: Close received (closed other: 0) on interaction [0x667210]<-0x660968
2018/08/20 04:14:50 [25008,25008] DEBUG: protocol.c(277): EventId=45147 Priority=DEBUG ProtocolSocket: triggering timeout on 0x667188
2018/08/20 04:14:50 [25008,25008] DEBUG: Operation.c(1208): EventId=45305 Priority=DEBUG MI_Client Operation Close: Complete session=0x7fffffffe550, operation=0x7fffffffe430, internal-operation=0x65df48
2018/08/20 04:14:50 [25008,25008] DEBUG: Session.c(519): EventId=45288 Priority=DEBUG Enter Session_Close with session (0x7fffffffe550), completionContext ((nil)), completionCallback ((nil)).
2018/08/20 04:14:50 [25008,25008] DEBUG: Session.c(779): EventId=45289 Priority=DEBUG Enter Session_AccessCheck - session (0x7fffffffe550)
2018/08/20 04:14:50 [25008,25008] DEBUG: Session.c(805): EventId=45290 Priority=DEBUG Leave Session_AccessCheck on session (0x7fffffffe550) with for operation (close session).
2018/08/20 04:14:50 [25008,25008] DEBUG: Session.c(552): EventId=45299 Priority=DEBUG MI_Client Session Close: session=0x7fffffffe550, internal-session=0x65da08
2018/08/20 04:14:50 [25008,25008] DEBUG: SafeHandle.c(207): EventId=45286 Priority=DEBUG Shutting down thunk handle: 0x65db28
2018/08/20 04:14:50 [25008,25008] DEBUG: InteractionProtocolHandler.c(979): EventId=45141 Priority=DEBUG InteractionProtocolHandler_Session_Close 0x65cdc8 (CompletionCallback 0x7ffff7ab5f16)
2018/08/20 04:14:50 [25008,25008] DEBUG: sessionmap.c(150): _SessionMap_IsValid - SessionMap initialized.
2018/08/20 04:14:50 [25008,25008] WARNING: sessionmap.c(313): SessionMap_Remove - Failed: 1
2018/08/20 04:14:50 [25008,25008] DEBUG: InteractionProtocolHandler.c(860): EventId=45145 Priority=DEBUG SessionCloseCompletion_Release 0x65ce68 count is 1
2018/08/20 04:14:50 [25008,25008] DEBUG: Session.c(638): EventId=45300 Priority=DEBUG MI_Client Session Close: waiting for all operations to shutdown session=0x7fffffffe550, internal-session=0x65da08, number left=0
2018/08/20 04:14:50 [25008,25012] DEBUG: protocol.c(2366): EventId=45158 Priority=DEBUG (U)Protocol _RequestCallback: closing 0x667188 after mask 10
2018/08/20 04:14:50 [25008,25012] INFO: protocol.c(2399): EventId=40012 Priority=INFO (U)Socket: 0x667188, closing connection (mask 10)
2018/08/20 04:14:50 [25008,25012] INFO: ../sock/selector.c(259): EventId=40033 Priority=INFO Selector_RemoveHandler: selector=0x7ffff7dd9340, handler=0x667188, name=BINARY_CONNECTOR
2018/08/20 04:14:50 [25008,25012] DEBUG: protocol.c(2373): EventId=45159 Priority=DEBUG (U)Protocol _RequestCallback: removing 0x667188 (mask 20, prev: a)
2018/08/20 04:14:50 [25008,25012] DEBUG: ../sock/sock.c(169): EventId=45349 Priority=DEBUG Sock_Close: sock (6)
2018/08/20 04:14:50 [25008,25012] DEBUG: InteractionProtocolHandler.c(537): EventId=45136 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Close 0x6607d8
2018/08/20 04:14:50 [25008,25012] DEBUG: InteractionProtocolHandler.c(569): EventId=45137 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Finish 0x6607d8
2018/08/20 04:14:50 [25008,25012] DEBUG: InteractionProtocolHandler.c(851): EventId=45144 Priority=DEBUG SessionCloseCompletion_Release 0x65ce68 with CompletionCallback 0x7ffff7ab5f16
2018/08/20 04:14:50 [25008,25012] DEBUG: protocol.c(366): EventId=45153 Priority=DEBUG (U)ProtocolSocket: 0x667188 _ProtocolSocket_Finish
2018/08/20 04:14:50 [25008,25008] DEBUG: Session.c(643): EventId=45298 Priority=DEBUG MI_Client Session Close: Completed session=0x7fffffffe550, internal-session=0x65da08
2018/08/20 04:14:50 [25008,25008] DEBUG: Application.c(424): EventId=45292 Priority=DEBUG MI_Client Application Close: application=0x7fffffffe530, internal-application=0x65c7b8
2018/08/20 04:14:50 [25008,25012] DEBUG: ../sock/selector.c(725): EventId=45065 Priority=DEBUG SelectorRun(Exit): 0x7ffff7dd9340
2018/08/20 04:14:50 [25008,25012] DEBUG: InteractionProtocolHandler.c(2460): EventId=45143 Priority=DEBUG InteractionProtocolHandler_Protocol_RunThread finished with return 0
2018/08/20 04:14:50 [25008,25008] DEBUG: ../sock/sock.c(169): EventId=45349 Priority=DEBUG Sock_Close: sock (3)
2018/08/20 04:14:50 [25008,25008] DEBUG: ../sock/sock.c(169): EventId=45349 Priority=DEBUG Sock_Close: sock (5)
2018/08/20 04:14:50 [25008,25008] DEBUG: Application.c(535): EventId=45296 Priority=DEBUG MI_Client Application Close: completed application=0x7fffffffe530, internal-application=0x65c7b8
root@jumping-ub14:~# 

```

**Comment by JumpingYang001** [comment]
**Update:**
Use `gdb --args /opt/omi/bin/omicli id`, then input `break SafeHandle.c:245` and press 'Enter' key, then input `run` and 'Enter' key, then input 'c' + press 'Enter' key for about 7 times when program finished, it works fine from miclient.log:
```
2018/08/20 06:26:04 [36353,36353] WARNING: null(0): SessionMap_Remove - Failed: 1
```

Use `gdb --args /opt/omi/bin/omicli id`, then input `run` and press 'Enter' key, it will get the thunk error:
```
2018/08/20 06:33:17 [37315,37315] ERROR: null(0): EventId=20106 Priority=ERROR Trying to thunk generic handle that has been shutdown already: 0x7fff5f7d31c0
2018/08/20 06:33:17 [37315,37316] WARNING: null(0): SessionMap_Remove - Failed: 1
```

Looks like a timing issue?

**Comment by JumpingYang001** [comment]
@palladia @paulcallen any suggestions? break in gdb works fine, but no-break in gdb will get error.

**Comment by JumpingYang001** [comment]
I think I need to add more logs between `Shutting down thunk handle` and `MI_Client Session Close: waiting for all operations to shutdown session`, will try to add more logs in SafeHandle.c.

**Comment by JumpingYang001** [comment]
Update my new log for error log:
```
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=45286 Priority=DEBUG Shutting down thunk handle: 0x15c49e0
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=50019 Priority=DEBUG Decrease refcount without release thunk handle: 0x15c49e0
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=50019 Priority=DEBUG Decrease refcount without release thunk handle: 0x15c49e0
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=45288 Priority=DEBUG Enter Session_Close with session (0x7ffdc5c55450), completionContext ((nil)), completionCallback ((nil)).
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=50020 Priority=DEBUG Increase refcount for thunk handle: 0x15c3ec0
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=50021 Priority=DEBUG Get correct thunk handle 0x7ffdc5c54638 from generic handle: 0x7ffdc5c55450
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=45289 Priority=DEBUG Enter Session_AccessCheck - session (0x7ffdc5c55450)
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=50020 Priority=DEBUG Increase refcount for thunk handle: 0x15c3ec0
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=50021 Priority=DEBUG Get correct thunk handle 0x7ffdc5c54588 from generic handle: 0x7ffdc5c55450
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=50019 Priority=DEBUG Decrease refcount without release thunk handle: 0x15c3ec0
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=45290 Priority=DEBUG Leave Session_AccessCheck on session (0x7ffdc5c55450) with for operation (close session).
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=45299 Priority=DEBUG MI_Client Session Close: session=0x7ffdc5c55450, internal-session=0x15c3dd0
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=45286 Priority=DEBUG Shutting down thunk handle: 0x15c3ec0
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=50019 Priority=DEBUG Decrease refcount without release thunk handle: 0x15c3ec0
2018/08/21 02:49:12 [5312,5312] DEBUG: null(0): EventId=45285 Priority=DEBUG Trying to thunk a handle after shutdown called: 0x15c49e0
```

good log:
```
2018/08/21 02:51:34 [5323,5323] DEBUG: null(0): EventId=45286 Priority=DEBUG Shutting down thunk handle: 0x55b9e0
2018/08/21 02:51:34 [5323,5323] DEBUG: null(0): EventId=50019 Priority=DEBUG Decrease refcount without release thunk handle: 0x55b9e0
2018/08/21 02:51:34 [5323,5323] DEBUG: null(0): EventId=50018 Priority=DEBUG Release thunk handle: 0x55b9e0
2018/08/21 02:51:34 [5323,5323] DEBUG: null(0): EventId=45138 Priority=DEBUG InteractionProtocolHandler_Operation_Close 0x561380
2018/08/21 02:51:34 [5323,5323] DEBUG: null(0): EventId=45152 Priority=DEBUG (U)ProtocolSocket: Close received (closed other: 0) on interaction [0x565f30]<-0x565e68
2018/08/21 02:51:34 [5323,5323] DEBUG: null(0): EventId=45147 Priority=DEBUG ProtocolSocket: triggering timeout on 0x565ec0
2018/08/21 02:51:34 [5323,5323] DEBUG: null(0): EventId=45305 Priority=DEBUG MI_Client Operation Close: Complete session=0x7fffffffdb30, operation=0x7fffffffd970, internal-operation=0x55df60
2018/08/21 02:51:34 [5323,5323] DEBUG: null(0): EventId=50019 Priority=DEBUG Decrease refcount without release thunk handle: 0x55b9e0
2018/08/21 02:51:34 [5323,5323] DEBUG: null(0): EventId=45288 Priority=DEBUG Enter Session_Close with session (0x7fffffffdb30), completionContext ((nil)), completionCallback ((nil)).
2018/08/21 02:51:34 [5323,5323] DEBUG: null(0): EventId=50020 Priority=DEBUG Increase refcount for thunk handle: 0x55aec0
2018/08/21 02:51:34 [5323,5327] DEBUG: null(0): EventId=45158 Priority=DEBUG (U)Protocol _RequestCallback: closing 0x565ec0 after mask 10
2018/08/21 02:51:34 [5323,5327] INFO: null(0): EventId=40012 Priority=INFO (U)Socket: 0x565ec0, closing connection (mask 10)
2018/08/21 02:51:34 [5323,5327] INFO: null(0): EventId=40033 Priority=INFO Selector_RemoveHandler: selector=0x7ffff7ff5470, handler=0x565ec0, name=BINARY_CONNECTOR
2018/08/21 02:51:34 [5323,5327] DEBUG: null(0): EventId=45159 Priority=DEBUG (U)Protocol _RequestCallback: removing 0x565ec0 (mask 20, prev: a)
2018/08/21 02:51:34 [5323,5327] DEBUG: null(0): EventId=45349 Priority=DEBUG Sock_Close: sock (6)
2018/08/21 02:51:34 [5323,5327] DEBUG: null(0): EventId=45136 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Close 0x561380
2018/08/21 02:51:34 [5323,5327] DEBUG: null(0): EventId=45137 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Finish 0x561380
2018/08/21 02:51:34 [5323,5327] DEBUG: null(0): EventId=45145 Priority=DEBUG SessionCloseCompletion_Release 0x55b9c0 count is 1
2018/08/21 02:51:34 [5323,5327] DEBUG: null(0): EventId=45153 Priority=DEBUG (U)ProtocolSocket: 0x565ec0 _ProtocolSocket_Finish
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=50021 Priority=DEBUG Get correct thunk handle 0x7fffffffcd18 from generic handle: 0x7fffffffdb30
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=45289 Priority=DEBUG Enter Session_AccessCheck - session (0x7fffffffdb30)
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=50020 Priority=DEBUG Increase refcount for thunk handle: 0x55aec0
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=50021 Priority=DEBUG Get correct thunk handle 0x7fffffffcc68 from generic handle: 0x7fffffffdb30
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=50019 Priority=DEBUG Decrease refcount without release thunk handle: 0x55aec0
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=45290 Priority=DEBUG Leave Session_AccessCheck on session (0x7fffffffdb30) with for operation (close session).
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=45299 Priority=DEBUG MI_Client Session Close: session=0x7fffffffdb30, internal-session=0x55add0
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=45286 Priority=DEBUG Shutting down thunk handle: 0x55aec0
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=50019 Priority=DEBUG Decrease refcount without release thunk handle: 0x55aec0
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=45141 Priority=DEBUG InteractionProtocolHandler_Session_Close 0x55aef0 (CompletionCallback 0x7ffff7e358f0)
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): _SessionMap_IsValid - SessionMap initialized.
2018/08/21 02:51:35 [5323,5323] WARNING: null(0): SessionMap_Remove - Failed: 1
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=45144 Priority=DEBUG SessionCloseCompletion_Release 0x55b9c0 with CompletionCallback 0x7ffff7e358f0
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=45298 Priority=DEBUG MI_Client Session Close: Completed session=0x7fffffffdb30, internal-session=0x55add0
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=50018 Priority=DEBUG Release thunk handle: 0x55aec0
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=50019 Priority=DEBUG Decrease refcount without release thunk handle: 0x55aec0
2018/08/21 02:51:35 [5323,5323] DEBUG: null(0): EventId=45292 Priority=DEBUG MI_Client Application Close: application=0x7fffffffdb50, internal-application=0x55a340

```

**Comment by JumpingYang001** [comment]
it seems different thread sequence cause the issue:
error log:
```
Increase refcount for thunk handle: 0x15c49e0
Increase refcount for thunk handle: 0x15c49e0
Increase refcount for thunk handle: 0x15c49e0
Decrease refcount without release thunk handle: 0x15c49e0
Shutting down thunk handle: 0x15c49e0
Decrease refcount without release thunk handle: 0x15c49e0
Decrease refcount without release thunk handle: 0x15c49e0
Trying to thunk a handle after shutdown called: 0x15c49e0
ERROR Trying to thunk generic handle that has been shutdown already: 0x7ffdc5c54640
Release thunk handle: 0x15c49e0
Decrease refcount without release thunk handle: 0x15c49e0
```
good log:
```
Increase refcount for thunk handle: 0x55b9e0
Decrease refcount without release thunk handle: 0x55b9e0
Increase refcount for thunk handle: 0x55b9e0
Increase refcount for thunk handle: 0x55b9e0
Decrease refcount without release thunk handle: 0x55b9e0
Shutting down thunk handle: 0x55b9e0
Decrease refcount without release thunk handle: 0x55b9e0
Release thunk handle: 0x55b9e0
Decrease refcount without release thunk handle: 0x55b9e0 
```

**Comment by JumpingYang001** [comment]
it shows I need to add lock in checking refcount to zero with release handle: https://github.com/Microsoft/omi/blob/29bf29c614fc8393ea778114634accf81adabbd7/Unix/miapi/SafeHandle.c#L177, will try it.

**Comment by JumpingYang001** [comment]
It is not lock issue.
I have found the error is in https://github.com/Microsoft/omi/blob/a3c43fd8958da05c1890b46feb448b7a39b0739b/Unix/miapi/Operation.c#L1321, will continue to investigate it tomorrow.

**Comment by JumpingYang001** [comment]
I have found the problem, the case think it will no operations after the shutdown, but the real case is that we have operation after shutdown: https://github.com/Microsoft/omi/blob/232a38192e16ca724f3f3438419f8ccaead10f34/Unix/miapi/Operation.c#L1288
