### ISSUE TITLE
[uninstall omi] remove omi will not remove all folders/files

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi#526]
when we use `dpkg -P omi` or `rpm -e omi`, it will remain some folders/files sometimes, when install new omi, it cause many issues like sockets folder permission issue, omi.keytab permission issue, etc.

```
root@ost64-ub16-01:~# dpkg -P omi
(Reading database ... 130855 files and directories currently installed.)
Removing omi (1.4.2.119) ...
Unconfiguring omid (systemd) service ...
Removed symlink /etc/systemd/system/multi-user.target.wants/omid.service.
2018-05-28 01:40:14 : Crontab no longer configured to update omi keytab.
Deleting omiusers group ...
Deleting omi service account ...
Purging configuration files for omi (1.4.2.119) ...
dpkg: warning: while removing omi, directory '/var/opt/omi/log' not empty so not removed
dpkg: warning: while removing omi, directory '/opt/omi/lib' not empty so not removed
dpkg: warning: while removing omi, directory '/etc/opt/omi/conf/omiregister' not empty so not removed
dpkg: warning: while removing omi, directory '/etc/opt/omi/conf/sockets' not empty so not removed
dpkg: warning: while removing omi, directory '/etc/opt/omi/ssl' not empty so not removed 
```

**Comment by palladia** [comment]
I believe this has been fixed.  Please re-verify.

**Comment by JumpingYang001** [comment]
we verified on latest build, on Ubuntu14 and Ubuntu16, the issue still exist.

**Comment by BingyuLiu** [comment]
@palladia, Hi George, this is easy to remove these folders/files. But we keep these files for many releases, it is by design or not? If not, I will fix it.

**Comment by BingyuLiu** [comment]
closed this issue by design.
